### PR TITLE
Added `active` prop to Tracking scripts, defaults to `true`

### PR DESCRIPTION
**Pull request by DanRossPhantom**
> Which issue, if any, is this issue related to?

e.g. "Closes #000" or "None, as it's a documentation fix."

> Is there anything in the PR that needs further explanation?

e.g. "No, it's self explanatory."

### CODE REVIEW

**Comment by PauloMFJ** [comment]
Does this work? Not sure you can defer loading like this? Couple issues:

If used in `_document`, you can't change `active` state.

If used in `Head` using `next/head`, and deferred loading till `active` was `true` believe GTM properties wouldn't load?

**Comment by DanRossPhantom** [comment]
> If used in `Head` using `next/head`, and deferred loading till `active` was `true` believe GTM properties wouldn't load?

We'd have to reload the page and the "active" state would have to be handled in a Context

**Comment by PauloMFJ** [comment]
`We'd have to reload the page` not ideal, unless this worked without doing so, don't think this is a valid solution. This might be doable in https://github.com/phantomstudios/next-gtm.

**Comment by DanRossPhantom** [comment]
Why is reloading unideal? It happens all the time when accepting/rejecting
cookies.

How else might we opt in/out of tracking?

Yes we could have something that prevents tracking events from firing via
that tracking function, but by this point the scripts have already fired
twice.

**Comment by PauloMFJ** [comment]
I've never accepted cookies and had to reload the page? As a user if I accepted it and it reloaded, would be super weird behaviour personally. This feels like a hack rather than a solution is my issue with it. But I agree it needs sorting, imagine there's a better way.

**Comment by digitaljohn** [comment]
Having to reload is not a good solution. Please research how it's supposed to be done. From a quick search on Google:
https://developers.google.com/analytics/devguides/collection/gtagjs/user-opt-out

**Pull request closed without merging**
